GITHUB_STATUS_REPORTER: true
JSON_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
TAP_REPORTER: true
VALIDATE_ALL_CODEBASE: false
FILTER_REGEX_INCLUDE: (.*.js|static/.*|routes/.*|views/.*|.*.md)
FILTER_REGEX_EXCLUDE: (tests/.*)
TAP_REPORTER_OUTPUT_DETAIL: detailed
TAP_REPORTER_SUB_FOLDER: tap
DISABLE:
  - PHP
  - SPELL
  - TEKTON
  - TERRAFORM
  - PERL
  - ANSIBLE