GITHUB_STATUS_REPORTER: true
JSON_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true
TAP_REPORTER: true
VALIDATE_ALL_CODEBASE: false
FILTER_REGEX_INCLUDE: (.*.js|static/.*|routes/.*|views/.*|.*.md)
FILTER_REGEX_EXCLUDE: (tests/.*)
JAVASCRIPT_ES_FILE_EXTENSIONS: [".ejs", ".js", ".vue"]
TAP_REPORTER_OUTPUT_DETAIL: detailed
TAP_REPORTER_SUB_FOLDER: tap
ENABLE:
  - BASH
  - JAVASCRIPT
  - JSX
  - PYTHON
  - SQL
  - TSX
  - TYPESCRIPT
  - CSS
  - ENV
  - HTML
  - JSON
  - LATEX
  - MARKDOWN
  - RST
  - XML
  - YAML
  - API
DISABLE:
  - PHP
  - SPELL
  - TEKTON
  - TERRAFORM
  - PERL
  - ANSIBLE